name: Docker Image CI/CD
on:
  push:
    branches: [ main ]
jobs:
  # 构建并上传 Docker镜像
  build:
    runs-on: ubuntu-latest # 依赖的环境
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build --platform linux/amd64 -t xyfacai/new-api .
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push xyfacai/new-api

  # Docker 自动部署
#  deploy-docker:
#    needs: [build]
#    name: Deploy Docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }} # 服务器ip
#          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
#          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
#          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
#          script: |
#            cd /home/server/one-api/internal
#            task release
#
#            cd /home/server/one-api/public
#            task release
          
            
